-- THIS CREATES THE CUSTOMER TABLE AND A UNIQUE INDEX
--
CREATE TABLE MM01.CUSTOMER
 ( CUSTNO        CHAR(6) NOT NULL,
   FNAME         CHAR(20) NOT NULL,
   LNAME         CHAR(30) NOT NULL,
   ADDR          CHAR(30) NOT NULL,
   CITY          CHAR(20) NOT NULL,
   STATE         CHAR(2) NOT NULL,
   ZIPCODE       CHAR(10) NOT NULL,
   PRIMARY KEY (CUSTNO) )
 IN DATABASE MMADBV;
--
CREATE UNIQUE INDEX MM01.XCUSTOMER
   ON MM01.CUSTOMER
    (CUSTNO)
   USING STOGROUP PUBSG001
   BUFFERPOOL BP1
   CLOSE YES;
