connect to SAMPLE user username using password;

DROP TABLESPACE TSEMP2;

CREATE TABLESPACE TSEMP2
      MANAGED BY AUTOMATIC STORAGE
      USING STOGROUP IBMSTOGROUP;

CREATE TABLE EMPLOYEE2 (
       EMPNO CHAR(6) NOT NULL,
       FIRSTNME VARCHAR(12) NOT NULL,
       MIDINIT CHAR(1),
       LASTNAME VARCHAR(15) NOT NULL,
       WORKDEPT CHAR(3),
       PHONENO CHAR(4),
       HIREDATE DATE,
       JOB CHAR(8),
       EDLEVEL SMALLINT,
       SEX CHAR(1),
       BIRTHDATE DATE,
       SALARY DECIMAL(9, 2),
       BONUS DECIMAL(9, 2),
       COMM DECIMAL(9, 2),   
     CONSTRAINT EMPNO_PK PRIMARY KEY 
     (EMPNO)		
	)
	IN TSEMP2;

connect reset;
